### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by valid22** [TunnelBlanket/Avalanche#1]
You'r hashing absolutely wrong! . I have fixed that, Here.

        def encryptPassword(password, md5 = True):
                if (md5 != False):
                        password = hashlib.md5(password).hexdigest()
		swappedHash = password[16:32] + password[0:16]
		
		return swappedHash

	@staticmethod
	def getLoginHash(password, rndK):
                Key = Crypto.encryptPassword(password, False);
		Key += rndK;
		Key += "a1ebe00441f5aecb185d0ec178ca2305Y(02.>'H}t\":E1_root";

		LHash = Crypto.encryptPassword(Key);
		return LHash;

**Comment by TunnelBlanket** [comment]
I fixed this in the **[dev](https://github.com/TunnelBlanket/Avalanche/tree/dev) branch**.
