### ISSUE TITLE
Using PDO except for dbapi and MySQLdb

### ISSUE THREAD

**Issue by valid22** [TunnelBlanket/Avalanche#4]
Source : http://sourceforge.net/project/showfiles.php?group_id=86244
PDO : Python Database Objects is much easy and efficient way to fetch values.

Look at this example.

```

import pdo
DBConn =pdo.connect('Module=MySQLdb;User=root;Passwd=;DB=,')
Results = DBConn.openRS("SELECT * FROM `penguins`")
testArray = []
while Results.next():
    testArray.append(Results.fields['ID'].value)

print testArray
```

```
>>> ['1','2','3','4','5','6']

```

**Comment by TunnelBlanket** [comment]
The last update to PDO was made in 2006.. 

Twisted's adbapi allows you to execute database queries in a non-blocking manner and pools connections to the database for you automatically.

**Comment by valid22** [comment]
Take a Look at my Database.py
[Database.py](https://github.com/TriCkle-C/Sprinkle/blob/master/Base/Database.py)
